import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Box } from '@mui/system';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry>
          <Header />
          <Box>
            {children}
          </Box>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  )
}
